FROM node:16 as build

MAINTAINER SDF Ops Team <ops@stellar.org>

WORKDIR /app

ARG REACT_APP_AMPLITUDE_KEY

ENV REACT_APP_AMPLITUDE_KEY $REACT_APP_AMPLITUDE_KEY

ARG REACT_APP_SENTRY_KEY

ENV REACT_APP_SENTRY_KEY $REACT_APP_SENTRY_KEY

COPY . /app/
RUN yarn workspace demo-wallet-client install
RUN yarn build:shared
RUN yarn build:client

# Copy the compiled static files out to an Nginx container, since we don't need any of the Node files.
FROM nginx:1.17
COPY --from=build /app/packages/demo-wallet-client/build/ /usr/share/nginx/html/
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf
