/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface StellarDemoWallet {}
}

declare global {


  interface HTMLStellarDemoWalletElement extends Components.StellarDemoWallet, HTMLStencilElement {}
  var HTMLStellarDemoWalletElement: {
    prototype: HTMLStellarDemoWalletElement;
    new (): HTMLStellarDemoWalletElement;
  };
  interface HTMLElementTagNameMap {
    'stellar-demo-wallet': HTMLStellarDemoWalletElement;
  }
}

declare namespace LocalJSX {
  interface StellarDemoWallet {}

  interface IntrinsicElements {
    'stellar-demo-wallet': StellarDemoWallet;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'stellar-demo-wallet': LocalJSX.StellarDemoWallet & JSXBase.HTMLAttributes<HTMLStellarDemoWalletElement>;
    }
  }
}


