name: Monthly dependency updates
on:
  schedule:
    # First of January, April, July, and October
    - cron: 0 0 1 */3 *

jobs:
  create_issue:
    name: Update dependencies
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Update dependencies
        uses: imjohnbo/issue-bot@3bee265982b87e730cf6c8dab7f86b68c92f8ef1
        with:
          title: "Update dependencies"
          body: |
            Update all project dependencies.
            ```
            yarn upgrade-interactive --latest
            ```
            Make sure there are no issues in the code editor, code compiles, and it runs without issues in the browser.
          pinned: false
          close-previous: true
          labels: "dependencies"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
